spring:
  application:
    name: users
  datasource:
    url: jdbc:postgresql://${POSTGRES:localhost}:5432/users
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  liquibase:
    change-log: db/changelog/master.yml
  jpa:
    open-in-view: false
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

server:
  port: 8081
  servlet:
    context-path: /users

app:
  jwtSecret: ${JWT_SECRET:someSecret}
  jwtExpirationInMs: ${JWT_EXPIRATION_MS:3600000}

logging:
  level:
    com.guavapay: debug
