spring:
  application:
    name: users
  datasource:
    url: jdbc:postgresql://${POSTGRES:localhost}:5432/users
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  liquibase:
    change-log: db/changelog/master.yml
  jpa:
    open-in-view: false

server:
  port: 8081
  servlet:
    context-path: /users

logging:
  level:
    com.guavapay: trace

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
