spring:
  application:
    name: orders
  rabbitmq:
    host: ${RABBITMQ:localhost}
    port: 5672
    username: user
    password: password
  datasource:
    url: jdbc:postgresql://${POSTGRES:localhost}:5432/orders
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  liquibase:
    change-log: db/changelog/master.yml
  jpa:
    open-in-view: false

server:
  port: 8082
  servlet:
    context-path: /delivery-order


logging:
  level:
    com.guavapay: debug

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_URI:localhost}:8761/eureka
