spring:
  application:
    name: orders
  datasource:
    url: jdbc:postgresql://${POSTGRES:localhost}:5432/orders
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  liquibase:
    change-log: db/changelog/master.yml
  jpa:
    open-in-view: false
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

server:
  port: 8082
  servlet:
    context-path: /delivery-order


logging:
  level:
    com.guavapay: debug
