server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: users
          uri: lb://users
          predicates:
            - Path=/users/**
#          filters:
#            - RewritePath=/users/(?<path>.*), /$\{path}
        - id: orders
          uri: lb://orders
          predicates:
            - Path=/delivery-order/**
#          filters:
#            - RewritePath=/delivery-order/(?<path>.*), /$\{path}
        - id: delivery-tasks
          uri: lb://delivery-tasks
          predicates:
            - Path=/delivery-tasks/**
#          filters:
#            - RewritePath=/delivery-tasks/(?<path>.*), /$\{path}

springdoc:
  swagger-ui:
    urls:
      - name: users
        url: /users/v3/api-docs
      - name: orders
        url: /delivery-order/v3/api-docs
      - name: delivery-tasks
        url: /delivery-tasks/v3/api-docs
    use-root-path: true

